// Sign in action
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOADING = 'LOADING';
export const SAVE_LIST_COURSE = 'SAVE_LIST_COURSE';
export const REMOVE_LIST_COURSE = 'REMOVE_LIST_COURSE';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const UPDATE_INFOR = ' UPDATE_INFOR';
export const UPDATE_INFOR_FAILED = 'UPDATE_INFOR_FAILED';
export const UPDATE_INFOR_SUCCEEDED = 'UPDATE_INFOR_SUCCEEDED';

export const SHOWLOADING = 'SHOWLOADING';
export const HIDELOADING = 'HIDELOADING';
