export const LOGINSCREEN = 'LOGINSCREEN';
export const HOMESCREEN = 'HOMESCREEN';

export const TABNAVIGATION = 'TABNAVIGATION';

export const SIGNUPVIEW = 'SIGNUPVIEW';
export const RESPASSVIEW = 'RESPASSVIEW';
export const QRCODEVIEW = 'QRCODEVIEW';
export const SETTINGSCREENS = 'SETTINGSCREENS';
export const ITEMGUARD = 'ITEMGUARD';

export const TRANSACTIONVIEW = 'TRANSACTIONVIEW';
export const GUARDVIEW = 'GUARDVIEW';
export const PARKINGVIEW = 'PARKINGVIEW';
export const IMAGEVIEW = 'IMAGEVIEW';
export const REVIEWSVIEW = 'REVIEWSVIEW';
export const REPASSWORDVIEW = 'REPASSWORDVIEW';
export const FILESVIEW = 'FILESVIEW';
